Dummy header
sslv-lv/sslv.lv pull request #4
Opened 2023-10-23 17:10 UTC by klek6

Created one of the headers, that are in https://docs.google.com/document/d/1-lkMUGR-SKRX0eRsQFvACO-QYLsCeGO2GrWUAPLWNmY for dummy code sake (looks)

2023-10-24 02:01 UTC, Jekabs-Leinis requested changes

2023-10-24 02:01 UTC, Jekabs-Leinis commented on src/common/components/SiteHeader.vue
> +  <RouterView />1
Typo?
```suggestion
  <RouterView />
```

2023-10-24 02:01 UTC, Jekabs-Leinis commented on src/common/components/SiteHeader.vue
> +  <RouterView />1
Probably should not be in header, but instead some root component, because otherwise, we're rendering the whole page from the header which is all kinds of weird

2023-10-24 02:01 UTC, Jekabs-Leinis commented on src/common/components/SiteHeader.vue
> +body, html {
Will have no effect with `scoped` style - see [the docs](https://vue-loader.vuejs.org/guide/scoped-css.html)

Probably should be moved to some global root component.

2023-10-24 02:01 UTC, Jekabs-Leinis commented on src/common/components/SiteHeader.vue
> +}
Could be slightly simplified with using `<style lang="scss" scoped>

Scss allows for subgroups of elements, like so
```
.navbar {
    color: blue;
    
    button { // will compile to .navbar button
       color: red;   
    }
}
```

2023-10-25 05:47 UTC, klek6 commented on src/common/components/SiteHeader.vue
> +  <RouterView />1
deleted

2023-10-25 05:47 UTC, klek6 commented on src/common/components/SiteHeader.vue
> +  <RouterView />1
deleted

2023-10-25 05:48 UTC, klek6 commented on src/common/components/SiteHeader.vue
> +body, html {
deleted as #app in main.css has something along those lines - deleting doesn't change header look

2023-10-26 11:10 UTC, Jekabs-Leinis approved these changes

2023-10-26 11:10 UTC, merged